spring.application.name=PropAudit-backend
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://database-1.czckqegsyqep.ap-south-1.rds.amazonaws.com:3306/propaudit
spring.datasource.username=admin
spring.datasource.password=Tulasi_garaga19
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8083
# ==============================
# AWS S3 Configuration
# ==============================

aws.access-key=YOUR_ACCESS_KEY
aws.secret-key=YOUR_SECRET_KEY
aws.region=ap-south-1
aws.bucket-name=propaudit-lease-documents